# Your Website Title
title: Zheng Qu

# Your Website URL
url: 'http://frankqz.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Zheng Qu
tagline: Ph.D. in Computer Engineering, IoT, Reverse Engineering
pic: myself.jpg # profile.png can be found at /assets/images/myself.jpg
description: Full Stack Developer, IoT, Reverse Engineering
description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: zhengqu.ece@gmail.com
website: frankqz.github.io # do not add http://
linkedin: linkedin.com/in/zheng-qu-009b761b1
github: frankqz
# twitter: '@realmelvinchng'
wechat: frank_zhengqu

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
